# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7701c268cf00feead024bb7819b75270ee828845f06c208bb7f5fa5c31ec9d9184d20fbe6f6c8a352c0db75cba6abc444825bc5ff267fb9aba9ff9df097de20a

test:
  secret_key_base: d5ed8df987a32224fe1526f720f5320197ca21a8dfc11934e2f26c5cd7010c4af8b5dad795b493d66a3304032f909c062f0f8741e6c8892b5934d037b1fb22b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
